apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: network-services-operator-system

resources:
- serviceaccount.yaml
- rbac.yaml
- deployment.yaml
- service.yaml

images:
- name: edge-gateway-ui
  newName: ghcr.io/datum-cloud/network-services-operator-ui
  newTag: latest
