apiVersion: v1
kind: Service
metadata:
  name: edge-gateway-ui
  namespace: system
  labels:
    app.kubernetes.io/name: edge-gateway-ui
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: network-services-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: edge-gateway-ui
    app.kubernetes.io/component: ui
