apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: edge-gateway-ui
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: network-services-operator
    app.kubernetes.io/managed-by: kustomize
  name: edge-gateway-ui
  namespace: system
