# This kustomization program is used to create all of the Milo IAM roles that
# are available to users.
#
# Each role should have a corresponding configuration file in this directory.

resources:
  - connector-admin.yaml
  - connector-viewer.yaml
  - gateway-admin.yaml
  - gateway-viewer.yaml
  - location-admin.yaml
  - networking-admin.yaml
  - networking-viewer.yaml
  - domain-admin.yaml
  - domain-viewer.yaml
