apiVersion: networking.datumapis.com/v1alpha1
kind: ConnectorClass
metadata:
  labels:
    app.kubernetes.io/name: network-services-operator
    app.kubernetes.io/managed-by: kustomize
  name: connectorclass-sample
spec:
  # TODO(user): Add fields here
