---
apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: networking.datumapis.com-connectorclass
spec:
  serviceRef:
    name: "networking.datumapis.com"
  kind: ConnectorClass
  plural: connectorclasses
  singular: connectorclass
  permissions:
    - list
    - get
    - watch
    - create
    - update
    - patch
    - delete
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Project
